echo:
  message:
    text: 'This is my PROD-849-589-485!!'
    label: "This PROD World OOps - 111"


spring:
  datasource:
    url: jdbc:h2:mem
    username: sa
    password:
    driver-class-name: org.h2.Driver
