echo:
  message:
    text: 'This is my PROD-849-589-485!!'
    label: "This PROD World OOps - 111"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/ecommdb
    username: pguser1
    password: pgpass1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
