echo:
  message:
    text: 'This is my PROD-849-589-485!!'
    label: "This PROD World OOps - 1122"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ecommdb
    username: pguser
    password: pgpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL

global:
  sport:
    name: "HOCKEY"
